# Generated by Django 6.0.7 on 2026-08-01 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tramites.tramite')),
            ],
        ),
    ]
