# Generated by Django 6.0.7 on 2026-08-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0003_eventooutbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='correo_responsable',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tramite',
            name='responsable',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
